/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_TIME_PB_H_INCLUDED
#define PB_TIME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Time { 
    uint32_t sec; 
    uint32_t nsec; 
} Time;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Time_init_default                        {0, 0}
#define Time_init_zero                           {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Time_sec_tag                             1
#define Time_nsec_tag                            2

/* Struct field encoding specification for nanopb */
#define Time_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sec,               1) \
X(a, STATIC,   SINGULAR, UINT32,   nsec,              2)
#define Time_CALLBACK NULL
#define Time_DEFAULT NULL

extern const pb_msgdesc_t Time_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Time_fields &Time_msg

/* Maximum encoded size of messages (where known) */
#define Time_size                                12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
