/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_TWIST_PB_H_INCLUDED
#define PB_TWIST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Twist { 
    float lx; 
    float ly; 
    float lz; 
    float ax; 
    float ay; 
    float az; 
} Twist;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Twist_init_default                       {0, 0, 0, 0, 0, 0}
#define Twist_init_zero                          {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Twist_lx_tag                             1
#define Twist_ly_tag                             2
#define Twist_lz_tag                             3
#define Twist_ax_tag                             4
#define Twist_ay_tag                             5
#define Twist_az_tag                             6

/* Struct field encoding specification for nanopb */
#define Twist_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    lx,                1) \
X(a, STATIC,   REQUIRED, FLOAT,    ly,                2) \
X(a, STATIC,   REQUIRED, FLOAT,    lz,                3) \
X(a, STATIC,   REQUIRED, FLOAT,    ax,                4) \
X(a, STATIC,   REQUIRED, FLOAT,    ay,                5) \
X(a, STATIC,   REQUIRED, FLOAT,    az,                6)
#define Twist_CALLBACK NULL
#define Twist_DEFAULT NULL

extern const pb_msgdesc_t Twist_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Twist_fields &Twist_msg

/* Maximum encoded size of messages (where known) */
#define Twist_size                               30

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
