#recovery_behaviors:
#  - name: clear_costmap_recovery/ClearCostmapRecovery
#    type: clear_costmap_recovery/ClearCostmapRecovery
#  - name: rotate_recovery/RotateRecovery
#    type: rotate_recovery/RotateRecovery

recovery_enabled: false