frequency: 10.
sensor_timeout: 0.2
transform_timeout: 0.2
two_d_mode: true
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map
transform_time_offset: 1e-7

imu0: /imu/data
imu0_differential: false
imu0_relative: false
imu0_queue_size: 5.
imu0_config: [false,  false,  false,
              true,   true,   true,
              false,  false,  false,
              false,  false,  false,
              false,  false,  false]

odom0: /wheel/odometry
odom0_differential: false
odom0_relative: false
odom0_queue_size: 5.
odom0_config: [ false,  false,  false,
                false,  false,  false,
                true,   true,   true,
                false,  false,  true,
                false,  false,  false]

odom1: /odometry/gps
odom1_differential: false
odom1_relative: false
odom1_queue_size: 5.
odom1_config: [ true,   true,   false,
                false,  false,  false,
                false,  false,  false,
                false,  false,  false,
                false,  false,  false]
